[pytest]
testpaths = automation/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --alluredir=allure-results
    --clean-alluredir
    -v
    -s
log_cli = true
log_cli_level = INFO
markers =
    smoke: marks tests as smoke tests
    regression: marks tests as regression tests